# 贡献者名录（临时版） {#aacontributors .unnumbered}

本书的编写和维护需要长久的贡献，大门永远敞开，欢迎加入我们。你可以：

- 贡献本书缺失的内容；

- 修改已有内容；

- 修改错别字；

- 其他任何跟书稿编写有关的工作。

向本书项目投稿的方法见附录\@ref(how-to-get-involved)。

- 主编：\@dapeng

- 副主编： \@maiyude

- 顾问（按字母顺序）：\@deanliu \@jademont \@lemooljiang \@oflyhigh \@rivalhw \@sweetsssj \@tumutanzi

- 编剧： \@maiyude

- 封面设计： \@maiyude

本书的各章作者、编辑、校对见各章节脚注。待书稿完成后，名单将汇总在这里。

**初级篇贡献者清单**

| 章节             | 作者                                                         | 编辑                       | 校对    |
| ---------------- | ------------------------------------------------------------ | -------------------------- | ------- |
| 第1章 新手第一步 | \@dapeng \@hepeng.chn \@incrediblesnow \@ivysrono \@maiyude \@oflyhigh \@vickylin \@wang-peilin | \@dapeng \@maiyude           |    \@jaffer     |
| 第2章 基本常识   | \@dapeng \@incrediblesnow \@maiyude\@vickylin \@wang-peilin \@woolfe19861008 | \@dapeng \@maiyude \@vickylin | \@meixia |
| 第3章 常用操作   | \@hepeng.chn \@lixing \@maiyude \@skenan                         | \@dapeng \@maiyude           |         |
| 第4章 文章编辑   | \@dapeng \@oflyhigh \@yellowbird                                | \@dapeng                    |         |
| 第5章 文章写作   | \@rivalhw \@tumutanzi                                          | \@dapeng \@maiyude           |         |




# 前言  ^[作者：\@dapeng，原文链接：https://steemit.com/cn/@dapeng/steem-handbook-preface] {#secpro .unnumbered}

**渊源**

就像很多个婴儿的出生一样，《Steem 指南：基础与开发》的诞生貌似来自一时冲动，其实是酝酿已久的厚积薄发。

刚来 Steem 的时候，作为新手，我看着旁边的人哗哗赚钱，而自己却一窍不通，于是急切地想了解关于 Steem 的一切。多次搜索之后，目标锁定在了  \@jubi 整理的[中文教程贴汇总](https://steemit.com/cn/@jubi/cn-steemit-wang) 和 \@carinewhy 整理的[中文steemit教學帖合集列表](https://steemit.com/cn-tutorial/@carinewhy/steemit)。当然，也许还有发布更早的，也许还有别人也整理过。当时对我而言，这两篇是帮助最大的。为了方便查阅，我在上面两个列表里删繁就简、去粗取精，有了一份属于自己的列表。

当时是 2017 年 7 月，中文区空前繁荣，写得更好、信息更新的新帖子层出不穷。于是，我在列表里加入了很多新内容，并重新分类，公布在每天的[“希望工程”日报](https://steemit.com/cn/@dapeng/steem-cn-project-hope-2017-09-27)里，以便帮助新人答疑解惑。

没过多久，这个列表被临时大鲸鱼 \@tumutanzi 收到了[新人直通帖](https://steemit.com/cn/@tumutanzi/5ndvpm-steemit)。后来，又被 \@jubi 整理到了 [steemit 中文导航站](http://steemit.wang/) 以及我的 steemr 小工具上。

然而，与此同时，CN 区却发生了几件密码被盗事件。最近的一次是 2018 年 2 月初。于是大家纷纷讨论账号的密码安全问题。而我当时的感觉是，这不是什么新问题，以前肯定有很多贴子讨论过。一看列表，果然。

一方面有那么多的帖子在讲“Steem 怎么用”，另一方面却总是出现问题，这是为什么？

我觉得，是缺少一套相对完整的、详细的、准确的教程或指南。以前整理的那些列表不够系统，各个帖子是不同作者单打独斗完成的，顾此失彼、相互矛盾是常有的事儿。这就导致这个列表的宣传力度不够。出了问题，很少有人去这个列表里找答案——即便去找，也不容易找到答案。

于是，编写一本系统的指南，这个想法就在我脑子里萌生了。

后面的事情，三言两语就可以说完：2018 年 2 月初，我们迅速搭建了协作平台和发布平台，编写了写作大纲，召集了志愿者，组建了编辑部，制订了写作规范（这一切写入了[《Steem 指南》实施纲要](https://github.com/pzhaonet/steem-guides/blob/master/shared/outline.md)）。大家热火朝天地干了起来。

**结构**

《指南》一书分三部分：初级篇，中级篇，高级篇。

**初级篇的关键词是“写作”**，面向的是即将注册和刚刚注册的新用户。

从浏览 steemit 网站开始，初级篇前两章告诉读者如何注册、登录和发布第一篇帖子，进而介绍一些基本常识，包括 Steem 上的货币、权力、声望、收益、带宽、关注、点赞、拉黑、踩灰、类目、标签、机器人等概念，以及互动、提款、保密等重要操作。第四到第五章，详细讲解了文章的写作方法和工具。

截至 2018 年 4 月初，“初级篇”基本完工，占 160 页， 6 万字。

**中级篇的关键词是“社交”**，面向的是对 Steem 有进一步需求的用户。

想尽快融入 Steem 社区的，可以从这里了解如何参加各种活动，如何注意社交里的言行，以及如何使用各种辅助工具和周边网站。

**高级篇的关键词是“开发”**，面向的是不满足于“发帖赚钱”的用户。

利用 Steem，你可以做见证人，可以研究 Steem 的数据库宝藏，可以开发机器人来代替人工，可以以 Steem 为基础搭建各种网站平台和应用。这些方法和实例在高级篇里有详细介绍。

除此之外，《指南》一书还包括"专题"和"附录"，来收录一些不易分类却很有价值的文章。

**关于书名**

本书最初起名“Steem 指南”，后来根据朋友们的提议，改为“Steem 基础与开发指南”。再后来，因为想把附录的部分章节单独整理成一本“Steem 指北：人物与八卦”，为了与之对应，本书改名为“Steem 指南：基础与开发”。

本书的英文名称最初是 **Steem Guides**，书的协作平台在 GitHub 上也是以这个命名的。很多朋友认为 guide 在这里应该用单数（所以本书的 logo 里用的是 **Steem Guide**）。我用复数的原因，就是因为当时我正在看一个名为 [GitHub Guides](https://guides.github.com/)的网站。后来，编辑部讨论，认为叫 **Steem Handbook** 更好，这基本上就是确定的英文名。

**阅读建议**

新用户可以先阅读第一章，对 Steem 有个基本概念后，就可以放下本书，去 steemit.com 发帖了。发帖时遇到任何问题或疑惑，再来本书找答案。然后边实践边阅读，这样收获最大，效率最高。

老用户可以扫一眼目录，摘取需要的章节阅读。书稿的在线网页版左侧有文档结构图，点击直达相关章节；顶部有搜索框，可以用来搜索需要的关键词。

本书所有章节都来源于发布在 steem 上的帖子。帖子的原始出处见章节标题的脚注（点击标题后面的上标数字即可）。在原始帖子里，你可以看到别人的留言，也可以留言跟作者互动。

如果在阅读中发现任何问题，包括内容的缺失、错别字、信息过时等，欢迎以任何形式跟我们联系。我们推荐方法是直接向我们的 github 项目提交PR，详见[书稿附录](http://steemh.org/how-to-get-involved.html)。

本书的编写和维护需要长久的贡献，大门永远向任何志愿者敞开。欢迎加入我们，一起把这本书做得更有价值。


# 区块链是凝固的时间（代序） ^[作者：\@dapeng，原文链接：https://steemit.com/cn/@dapeng/79z9jz-or] {#secpre1 .unnumbered}



（1）

昨晚，看到 [\@catwomanteresa 关于钱包被盗的帖子](https://cnsteem.com/steemit/@catwomanteresa/my-sbd-and-steem-is-stolen-steemit)，和 [\@rivalhw 谈新人心态的文章](https://cnsteem.com/cn/@rivalhw/23b9qu)，我就上了一下久违的微信群，想看看来龙去脉。

1800 条未读信息，从头到尾扫了一遍，最后发现，我想知道的东西，包括被盗的前因后果以及新人遭遇的这些困惑和困境，都已经写在帖子里了。什么新人收益少啦，抱团取暖啦，新帖求赞啦，等等等等问题，老人们都遇到过；老人们陷进去的那些坑，新人们一个也躲不开。用 \@tumutanzi 博客的标题来讲，“日光之下，并无新事”；用李白的话来说：

> 今人不见古时月，今月曾经照古人。

既然都是老问题，那么前人的经验教训，为什么对后人没啥用处呢？

（2）

客观上来说，是网站的设计造成的。不管是哪个 steem 网站， steemit.com，cnsteem.com，busy.org，全部优先展示新文章，连个置顶或收藏都没有；只有 chainbb.com 是分页显示所有文章，我以前就是去那里翻旧帖。于是乎，老生常谈的话题，每拨新人写一轮，重复地写，其实早就被前人写尽了。

从这个角度来说，本文也是如此。去翻翻旧帖，无数是写给新人的，而当年读这些帖子的新人，如今也成了老人。

而主观上来说，在困惑的时候，新人们的选择是提问和抱怨，而不是自己找答案。实际上，答案早就被一轮一轮地摸索过了，只是没有摆在眼前，搜起来不方便。


如果你只盯着眼前，会感觉每天的帖子像瀑布一样刷刷流过，别人呼呼赚钱，让你手足无措，唯恐被世界抛弃。

这时不妨离远一点看，会欣然发现，steem 上的时间其实是凝固的。如今的大神们，他们当年的一笑一颦，举手投足，全部定格在区块链上，抹都抹不去，如圈圈年轮，如沉在地下的恐龙脚印。你的现在是他们的过去，他们的现在是你的未来。

就像电影《降临（Arrival）》里讲到的外星人语言。只要你从另一个维度去解读，就会看到，过去、现在和未来浑然一体。


（3）

写到这里，我停下来，读了读上面的文字，发现自己又开始倚老卖老了。

不记得什么时候起，开始感到自己不是新人了。可能是从发起“新人希望工程”和“新人三个一”活动吧。这就好比一个女孩，直到成为妈妈的那一天，才突然发觉自己已然不是孩子了。

从活动里，我发现了一大批热情参与、认真写作的新人，\@winniex 就是其中一位。昨天，她在[百天帖](https://cnsteem.com/cn/@winniex/100)里写道：

> 前两天看到一个 56 的被称前辈好想笑，想起自己在四十几的时候就盼着到 50，......嗯，现在我59了，如果不是最近来了老多新人，我还想称自己是新人。。。

每次读 \@winniex 的文字，我总是捕捉到一丝小哀怨，还有一点看破红尘的淡泊。

而比她早来一点的 \@yingpingzhang 在犹豫，不知以后在 steem 上往哪个方向走。他写道：

> 以前只想玩音乐，后来生活所迫，转战IT。现在只想潜心研究区块链，怎奈大家更喜欢我的音乐。

造化弄人啊。林妹妹和宝姐姐，到底喜欢哪个多一些？可知当你在为此烦恼时，气坏了多少单身狗。区块链是什么，无数人连听都没听说过哩。

弹吉他唱歌的帖子，喜欢文字的人不一定喜欢，但自有弹吉他的人点赞；

谈区块链的帖子，弹吉他的人不一定喜欢，但自有喜欢投资的人点赞。

这种事儿，很多前辈都遇见过。看看他们怎么处理的就好了。

（4）

大神也是人，不可能看得见每个新人。从社区角度来讲，需要传帮带，各司其职，[小鱼评、大鱼荐、大鲸赞](https://steemit.com/cn/@dapeng/what-are-you-on-steem)，才能达到整体效益最大化。而从个人角度来说，想在 steem 上赚钱，要么就花钱买 SP，要么就练笔写出好文字，这是性价比最高的两条路。其他的出路，我觉得是得不偿失。——当然，这还取决于你对“得失”的定义。

看，我又倚老卖老了，不好意思。其实我也只不过在 steem 上混了不到半年而已。现在，已经有朋友管我叫“前辈”、“大牛”，吓死我了，赶紧说“别这么叫我”。后来一想，刘美女 \@deanliu 也不让我叫他前辈。不知道刘美女是不是也管更早的人叫前辈。

刘美女曾经说过，他对新人的注意大概就是到我这一拨，后面的关照不过来，不是不想，而是精力有限（其实刘美女仍然在尽力照顾后来的新人，例如 \@yingpingzhang 等）。而我的注意力，大概也就是到 @winniex 这一拨，后面的新人层出不穷，若非文章写得特别好，记都记不住。

而关于举办活动，\@rivalhw 发文写道：

> 很多时候我们不是因为有希望了才坚持，而是因为坚持了才有可能看到希望啊！　

《Steem 指南》一书的编写，就是一项集体参与的活动。本书，就是活动的成果。

参加者里面，有没有你？

\mainmatter
