# (PART) 初级篇 {#cjp .unnumbered} 

# 新手第一步 {#xsdyb}
## 浏览 steemit 网站 {#ll_steemit_wz}
小雅在朋友的介绍下来到了Steemit。

steemit是什么？其实小雅也没搞明白，朋友对她说了很多，很多区块链，什么去中心化，什么未来趋势云云，但是小雅一句都听不明白。但是朋友说的话有一句话小雅听明白了，就是在Steemit写文章可以赚钱。写文章可以赚钱？那自然是好事。于是小雅就在朋友的介绍下登陆了steemit。

steemit给小雅的第一印象是一个乱糟糟的博客，而且还是全英文的。虽然小雅英文水平还算可以，但是如果有中文支持她会更开心。小雅随便看了看首页的文章，发现大多都是全英文的文章，偶尔才有一两篇中文的文章出现。

难道在这里的都是外国人？在这里写文章要用全英文吗？抱着一大堆的问号，小雅点击了注册新账号按钮。

## 注册 steem 账号 {#zc_steem_zh}
小雅有点烦躁，因为她在注册Steemit账号遇到了难题。

这是她见过的注册账号最不友好的社区。她从来没有想过注册一个账号会是那么麻烦的一件事情，她甚至萌生了永远不登陆这个网站的想法。

首先这个网站的浏览速度超级慢，至少在中国访问的速度是超级慢，她感觉回到了拨号上网的时代。其次，注册个账号居然需要翻墙来收取验证码。天啊，她一个小女生哪里懂得翻墙这些高科技的事情啊。

好不容易在朋友的帮助下翻了墙，又专门去注册了一个Gmail的邮箱用来收取验证码，按照步骤一步步的完成注册。忙完这些，她发现刚注册的账号居然还不是马上生效，还要等待官方把你的账号激活，这个过程一般是1-7天左右。

小雅很是抓狂，终于在第三天的早上，她终于收到了官方发来的邮件，她的账号正式开通了。

虽然历经波折，但是小雅的Steemit之旅正式开始。

## 登录和保存密码 {#dlhbcmm}
小雅好不容易注册好了steemit账号，终于可以开始她的steemit之旅了。

她首先按照网站的说明把那长达二十多位的密码抄了在一个小本子上。网站上一再提示这个密码非常的重要，遗失了几乎不可找回，这让小雅有点心惊。因为小雅忘记的账号密码不计其数，忘记的概率远远大于被盗的概率，很多久不登陆的账号她都是通过重设密码才找回的，这个网站的密码不可找回让她有点担忧。小心驶得万年船，她把密码抄了下来，又在加密的云盘上保存了一份，她想着这样应该不会忘记了吧。

忙完密码的事情，她寻思着如何装修一下自己的个人主页。

## 设置个人基本信息 {#szgrjbxx}
小雅掉进了自己账号的设置页。

Steemit的各种设置和博客有点类似，虽然小雅的博客随着微博微信的兴起荒废多年了，但是小雅以前可是一个博客迷呢。

首先要设置的是头像，小雅打算使用她在微信用了多年的头像。但是她马上就遇到了一个难题，她找不到上传头像的地方。经过一番摸索，原来只要把头像图片的网址复制到设置页就可以了。原来那么简单，小雅暗暗嘲笑自己的愚蠢。

接下来小雅填写了一些自己的基本信息，然后继续设置自己主页的banner，因为图片尺寸的问题，小雅在这花了很长的时间才完成。终于弄完这些基本设置，小雅顿时松了一口气。

小雅还看见设置里面还有钱包的选项，里面有各种货币和选项，在账号安全里面还有好几个不同种类的密码。这些没设置过没见过的选项让小雅有些头疼，她决定暂时不管，日后慢慢研究，现在先发帖再说。

## 第一帖 {#dyt}
## 延伸阅读：steem 的魅力 {#steemdml}

