# 基本常识 {#jbcsp_}
## 什么是 steem {#sms_steem}
小雅的第一篇文章发出去之后，只有寥寥几个人给她点了赞，收益也只有可怜的0.03美元，这让她有点失望。

不过她很快就从失落中走了出来，自己还只是个新人嘛，没人关注是很正常的事情，加油写文章就是。

她转而研究steemit里面的各种钱。她发现这里的居然同时存在三种钱，分别是steem,steem power（sp）,Steem Dollars（SBD）。为什么一个社区内会同时存在三种钱啊？这让小雅很是困惑，这就感觉像是市场上同时流通三种人民币的感觉，初次接触区块链的小雅完全搞不懂为什么。

不过让小雅感到更为困扰的事情是，自己所有的钱币都是0，这让小雅顿时失去了研究这些货币的兴趣，默默的继续写文章去了。

## Steem上的各种货币（本文部分引用自@rivalhw的文章）
### 概述
在Steem区块链上我们使用3种货币，Steem，SBD(Steem Dollars)，SP(Steem Power)**（注：严格意义上讲SP不能算作一种货币，因为它不能随意流通和交易，这里把它归为货币主要是为了方便理解，具体请见下文SP的单独讲解）**。为什么一个区块链上要使用三种不同的货币呢？这主要是因为它们被赋予不同的权利，拥有不同的功能，下面我们依次介绍。
### Steem
Steem是Steem区块链上的基础货币，另外两种币都跟它相关。你可以通过在Steemit.com，cnsteem.com等网站上写文章，评论或点赞来获得它。你可以在任何时间存入，取出或者与其它持有者交易Steem。Steem可以通过一个叫Power up的过程转化为SP(Steem Power)。
### SP(Steem Power)
如上文所述，SP是Steem通过Power up的过程获得的。顾名思义，你的SP越多，你在Steem社区上的影响力就越大，你的SP越大你的点赞就越可以得到更大的收益。具体来说，按本文编辑时的实时行情，如果你有10000SP，那你的一个点赞最多可以产生 $2.8 左右的收益。而实际收益其实远大于显示收益，显示为 $2.8 的收益实际上大概相当于7.7美元(具体原因请看下面SP的介绍)。那既然SP这么有用，为什么不把Steem全部转为SP呢？这是因为SP缺乏流动性，不能随意取现及交易。如果我们想把SP卖掉，则需要进行一个Power Down的过程，将SP转化为Steem再进行交易。而整个Power Down的过程每周只能将你持有的13分之1的SP转化为Steem，所以当您有了一些Steem后，还是要具体情况具体分析要把自己多少比例的Steem转化为SP。
### SBD(Steem Dollars)
SBD初衷是设计来1：1兑换美元的，官方现在也是把1SBD固定视为1美元的。但实际上它的市场价格却是像Steem一样波动的，现在1SBD的市场价远大于1美元。这也造成了文章作者获得的实际收益远大于显示收益。以上文所说显示收益 $2.8 为例，实际收益为1.4个SBD和价值为1.4美元的SP，而按本文编辑时的市场价格，1个SBD约等于4.5美元，所以实际收益应为4.5x1.4+1.4=7.7美元。
### 怎么获得这些货币
作者在发文章之后，按照Steemit的规则，7日后文章将被锁定无法修改(区块链永久不可篡改性)，同时进行该帖的结算，并根据作者发帖时的设定进行Steem和SBD的奖励。如果作者选择50% 50%，系统会将奖励分为两部分，一部分作为SBD奖励，另一部分作为SP奖励；如果作者选择发帖时power up 100%，则系统将会将奖励全部按照SP进行power up。当然你也可以通过交易所或其它货币持有者交易来获得这些货币。
### 总结
Steem上的货币是相互依存，息息相关的，新手朋友光看这些文字可能还是不能完全理解。如果你想投资进来我建议可以先投资一小部分自己实际操作一下，完全搞清楚这里面的各种关系后再决定是否大力投资。

## 关于声望的一切 {#gwqwdyq}
小雅来到Steemit已经好几天了，文章也发了好几篇了。虽然点赞的人不多，每篇文章的收益也就零点零几美元，不过小雅也很满足了，因为自己已经慢慢开始熟悉这个社区了。

小雅今天发现了一个事情，就是自己名字旁边有个括号，里面写了一个数字。她记得刚来的时候这个数字是25，今天这个数字变成了26。这让她很是好奇，她把鼠标悬停了在数字上面，屏幕显示出了一行文字“这是小雅的声望分数，信誉评分取决于收到的投票历史记录，用于隐藏低质量的内容。”

“声望？这是什么？”小雅喃喃自语道。小雅把这个理解为类似等级的东西，只要自己好好写文章，这个等级会上升的吧。但是屏幕提示的最后一句话“用于隐藏低质量的内容”，让她有点不明白，难道这里的声望会出现负数？出现了负数后账号会被隐藏吗？

看来小雅需要学习的内容还有好多。

## 关于文章收益的一切 {#gwwzsydyq}
今天是小雅来到Steemit的第7天了。今天发生了一件事情让小雅很是兴奋，那就是小雅收到了第一笔付款。虽然这笔钱只有可怜的0.015SBD，但是小雅还是很开心，因为自己的账户总算不是零了。

不过小雅因此产生了一个新的疑问，这里的收益是怎么计算的？自己收到的这笔钱是第一篇自我介绍的收入，她的那篇文章的收入是0.03美元。文章上写的是美元，但是发来的却是SBD和SP。而且这比例也不知道是如何换算的，0.03美元的文章换来了0.015SBD。小雅算了算，获得的SBD大概是美元价格除以2。但是自己还获得了零点零几的SP，这又是如何换算的？

小雅越算越烦恼，越算越不明白，最终她决定放弃计算收益，反正有钱收就好，算的那么明白干什么呢？

## 关注、点赞、拉黑、踩灰 {#ysyd_gz_dz_lh_ch}
收到钱让小雅很是开心，这大大的激发了她对Steemit的热情。她打开了网页，开始浏览别人的文章。

小雅对于给别人点赞从来不吝啬，基本上她看过的文章都点赞了。其中她觉得文章写的很有趣的人，她会点击“关注”，当然她更加希望别人会回关她。但是点赞的过程中她又产生了新的困惑，就是刚开始她点赞别人的收益会增加0.01美元，到了后来，就完全不增加了，这让小雅非常的困惑。不过小雅很快就抛开了这个困惑，想不通那就别想。

她还发现了文章上面有一个小旗子，她好奇的点了点，居然发现别人文章收益减少了。看来这个按钮是踩别人用的，自己没事别乱点这个按钮，以免得罪人了。

Steemit里面的门道真多，小雅觉得自己需要学习的地方真是太多了。

## 类目和标签 {#lmhbq}
小雅已经慢慢熟悉了Steemit社区，在这里，她每天都会发现一点新东西。

这天，她如同往常一样在编辑文章。在准备发布的时候，她留意到了一个事情，就是标签。这个标签其实从最初写文章的时候就要求填写，但是小雅每次填写都非常随意，今天她不知道为什么特别在意起了这个事情。

小雅直觉的认为，这个标签应该是文章的一种分类，那样的话，自己就不应该随意填写标签，要有一个细致的分类。于是她开始研究别人文章的标签如何写的。研究中她发现了一个有趣的标签，那就是很多中文的文章里面都有一个“cn”的标签，这个发现犹如发现新大陆一般让她兴奋。她点进去cn的标签一看，发现cn标签里面全是中文的写作者，这顿时让她有种找到组织的感觉。

在这之后，小雅的所有文章都加上了“cn”的标签，给她点赞的人也慢慢多了起来。

## 大鲸和小鱼 {#djhxy}
最近小雅在浏览别人文章的时候发现了一个有趣的词语，那就是“大鲸”和“小鱼”。

小雅发现很多新人喜欢称呼自己为“小鱼”，而很多Steemit的老前辈被尊称为“大鲸”。这个现象小雅觉得很有趣，用海洋动物来取代等级给人的感觉非常的可爱。但是同时小雅也很疑惑，他们是如何判断一个人是大鲸还是小鱼的呢？

为了解开这个谜团，小雅进行了一系列的明察暗访。最终发现这个等级是按照SP的大小来划分的，大鲸就是这里最高等级的人了。然后小雅好奇的按照了这个等级划分把自己归类，发现自己是最低等的浮游生物，连小鱼都不是，这让小雅有点哭笑不得。小雅暗暗的给自己定下了一个目标，总有一天自己要成为一条大鲸！

## 机器人和小号 {#jqrhxh}
小雅像往常一样勤奋地更新文章，在仔细地检查了文章的错别字后，小雅按下了“POST”的按钮。然后小雅再次浏览自己的文章。翻到后面，发现居然已经有一个人在后面评论了。

小雅感到惊喜的同时又有一丝好奇，是谁在自己文章刚发出就过来评论了呢？小雅仔细读了读评论，是一段英文。翻译过来的意思就是“我是一个机器人，已经给你点赞了，希望你也可以来回访我。”这让小雅更加惊讶了，这居然是一个机器人？Steemit社区居然还有机器人在活跃，这太超出小雅的想象力了。

小雅顺着机器人的主页一路摸索过去，发现这个机器人的主人叫做大辉，是一个程序员，这个点赞机器人就是他开发的。小雅对机器人充满好奇的同时，也对这个叫大辉的人充满了崇拜。

## 禁忌和审核 {#jjhsg}
今天小雅非常的难过。为什么呢？因为小雅今天被一条大鲸踩了一下。

这大鲸一踩可不得了，首先自己的文章直接变成了灰色，成为了不可浏览的状态，然后自己的声望等级还直接掉了2级那么多。

这位大鲸同时给小雅留了言，“请不要使用没有版权的图片，而且你用的还是我的图片。”小雅有些纳闷，怎么自己就那么倒霉刚好用了大鲸的图片呢？不过这也让小雅警觉起来，在这里的所有人都非常注重原创性和版权的问题，自己这样随意的使用别人的图片是很危险的。小雅反思了一下自己的行为，诚恳的给大鲸道了歉。这位大鲸也非常的通情达理，一番沟通后撤销了对小雅的踩。

经过这次小风波后，小雅写文章的时候，不时会提醒自己，要常记“原创”二字。

