# 文章写作 {#wzxzp}
## steem 上适合写什么 {#steem_skgxsm}
## 如何创作优质内容 {#rhczyznr}
### 1、steemit优质内容的社交性
很多从公众号、简书、微博等其它传统内容平台过来的作者们容易在一开始就对steemit产生一些误读。

>误读：steemit是一个类似微博、微信朋友圈那样的重社交网络。
现象：像微博那样发帖子，一篇文章几句话，或者配一张简单的照片。对于很多刚刚来steemit的新手来说经常可以看到这样的内容。

>误读：steemit是一个类似公众号、简书那样的写作平台。
现象：像公众号和简书那样发长长的一篇文章，文章质量很高，但是关注和点赞确很少。

对steemit的正确理解它是一个“**内容社交**”网络平台。首先，steemit里需要有“内容”，其次，steemit有很强的社交性。

在steemit里“内容”与“社交”是相辅相成的，大家通过每个人长期的内容文字，大概了解在你文字下你是怎样的一个人，大家有共同的兴趣、价值观或者共同的利益（比如赚钱）然后关注（follow）你产生社交，然后由已建立的社交关系，持续关注你的文章内容。对于个人想要提高自己的被关注度，也需要主动去社交，比如主动去阅读他人文章点赞评论留言等。

steemit不是一个熟人关系的网络，不能像微信朋友圈那样的发张照片写段简单的文字记录自己的日常生活，在steemit里这样的内容不是优质内容。同样的，一篇长长的有深度有内容的文章而没有因社交传播出去，在steemit也不算优质内容。

steemit里的优质内容是跟社交有强烈关联的。steemit里常常可以看到一篇都是程序代码的文章，对于不少非程序员的人毫不夸张的来说一点儿都看不懂，这是优质内容吗？对于长期写干货文章的人来说，看到一篇旅游帖的收入很高，完全不能理解，在他们眼里那是优质内容吗？

在steemit里程序代码、旅游帖、绘画等内容都有很强的社交性，都可以通过内容连接起来同样一批兴趣相投的人，这些可以产生社交的内容在steemit里都是优质内容。

### 2、steemit优质内容的易读性
易读性主要体现在文章的排版，内容的图文并茂上。

具体操作：

* 熟练运用markdown编辑文章；
* 屏读时代文章段落可顶格不空字符，一段文字行数不宜过多，一般三四行文字一段为宜；
* 尽量轻量化写作，控制文章字数，一般控制在1千字为宜；
* 尽量多些实际的故事，少些无病呻吟的干道理；
* 多插入跟文章内容相关的高清图片，字数超过一千字可以考虑插入多张图片，插入的图片注意比例尺寸（一般以横屏图片为宜）及居中显示等。

### 3、steemit优质内容的传播性
* 给文章取一个好的标题

往往一个好的标题就顶半篇文章，一篇好的文章标题，或许就决定了你的文章有没有人看。那么如何给文章取一个好的标题，我们来看看steemit里那些曾经出现过的比较好的标题：

比如来看看@coldhair的文章标题:
 
>慢性浅表性胃炎，怎么办？
你写一篇Steemit文章需要花费多少时间？
如何坚持在Steemit上写文章？
Steemit团队有可能掏钱跑路？

仔细观察你会发现，coldhair的文章标题大多都是问句，问句的标题有个好处是能给读者引发疑问，疑问句标题的文章能切重读者关心点跟读者产生共鸣。

>父亲又吸烟了

交代了人物和基本的故事，一个“又“字也又让人感受到作者的情绪。简单几个词，包含的故事信息量确很大，让人忍不住想阅读。

比如来看看@tumutanzi的一些文章标题：

>复杂的英国，为砍一棵树导致民众和政府冲突
一个有意思的澳大利亚Uber司机：了解红灯区、会治病、爱拍照

民众、政府、冲突，红灯区.......通过一些敏感刺激的词，吸引你这里还有故事。

>我把群主宝座禅让给两个英国人的爹
看牙医记：牙医建议我多吃软饭

幽默，不直接写把steemit群主转给justyy而要绕个弯儿，注意饮食说是吃软饭。

>在Steemit上写作一年能有36万收入？
36万吸引眼球。其实文章想表达的思想可能跟36万没关系。

比如来看看@yellowbird的一些文章标题：

>毕业六年，酒精考验
长这么大，第一次被人约跑

践人，酒精考验，约跑，文字游戏，故意让你读错引起兴趣。

>BeeChat一个区块链的微信？
币问——币圈的知乎

介绍一个新事物，类比一个熟悉的事物降低认知难度

>我接了个陌生电话

制造悬念，引入一个故事。

* 文章内容把握当下热点

这个非常好理解，比如我们常见的娱乐新闻事件，都是热点追踪的。当你也需要对某些事件发表看法，也尽量把我热点，而不是当热点过去许久后，再来发表文章。

比如steem项目团队最新又有什么开发进度等都属于需要把握当下热点的内容，当热点过了再来评价事件如何，即使内容很深入但是也许已经不适用新的环境，也不属于优质内容。

### 4、优质内容的两个作用：渡人渡己
前面几点都是谈的优质内容面上的点，优质内容最核心的还是要体现在内容上，我认为，优质的内容主要有两点：渡人渡己。

你写的文章对自己有用，让自己思考，感悟，启发，解脱，成长，愉悦等等；
你写的文章对他人有用，对他人是有用的信息，给他人启发，思考，感悟，成长，愉悦等等。

### 5、小结

最后总结一下，如何在steemit创作优质内容：

**了解steemit“内容社交”的平台特性，建立一个写文的良好心态，把握度人度己的内容原则，做好文章的易读性，传播性，社交性。**



## 外文写作和国际化 {#gjh}
小雅在烦恼文章质量的时候，同时也在考虑如何把文章写得国际化。Steemit虽然中文区非常活跃，但是这终究是一个国际性的平台，中文用户还是占少数，要想文章能够更好的传播，用双语写作看来是有必要的。

但是这也给了小雅一个很大的挑战，小雅的英文水平只能说一般，小雅经过那么多年的义务教育学习英语，考试做题就厉害，但是说到实际应用，那个水平还是差远了。但是不会就学是小雅一贯以来的作风，她决定从今天起所有文章都要开始用双语写作，不会的地方就查字典，多写多练自然就会了。

就这样，小雅在坑自己的路上越走越远。
****

在小雅以及很多前人的帖子里，都提到了外文写作的问题，最终结论就是：好好运营中文内容可以过得很好，但你如果英文好，可以过得更好。

steem作为一个全球性的自媒体平台，上面大部分用户都是英文用户，这让很多国人望而却步，更何况还有很多人都不知道！克服掉语言障碍，找到翻墙软件，再各种注册（还不定注册的上），还要面临不熟悉的steem平台规则，说实话，留下来的都是真爱啊！要不要发展外文写作，关键还是自己想在steem上怎么玩。

#### 1、尊重差异文化

发帖礼仪是必须得，这里我们要说的还是大家都知道的尊重文化差异，比如不要发谩骂侮辱别国文化和什么什么政治的文章，不喜欢可以礼貌点赞，总之，别犯罪！

#### 2、英文好的请多在中文区以外多发掘机会
英文好，那就多结交点外国朋友，英文好，可以写中英文blog，便于更多的用户阅读，当然，英语本身也只是工具，只要善于勇于交流，也可以结交很多外国朋友的，有好的创意和想法，跨界垮国都不是问题。

#### 3、少用机器翻译
有些人喜欢用谷歌翻译，但机器翻译的质量并不高，如果直接用在了文章里，只会直接降低你的文章逼格，不过本来文章逼格就不高的就算了，主要是会影响用户的可读性。总之，机器翻译的质量不高，别直接大片大片的贴，至少也得要改吧改吧再贴。不过对于英文差的，我指自己翻译得比机器还差那种，也不妨借鉴一下，至少单词拼写是准的，所以，还是努力提高英语吧。

#### 4、不要为了想要更多点赞而胡乱翻译
这个可能事很多新人最容易犯的问题，但也是最值得赞赏的举动，前提就是，翻译要准确。仅仅为了吸引更多的观众，把标题强行翻译是没必要的，如果一定要翻译，就把标题翻译准确吧。

#### 5、寻找一个擅长的专题

寻找一个擅长的专题进行运营会更容易成功，无论是中文写作还是外文写作，这个都是可借鉴的。比如@sweetsssj专门写旅游博客，@yellowbird专门发桥梁设计技术贴等等，专注一个专题可以容易让别人记住你，也更容易形成自己的写作兴趣点。

#### 6、得到国外点赞团队的支持

国外点赞团队的支持，可以极大的提升你的投票权重，中文圈里知名的sweetssj在得到国外点赞团队的支持后，就从小鱼变成了大鲸，当然和她之前长久的博客积累是紧密分不开的，所以用心经营自己的账号和内容，说不定哪一天就被国外团队发现，改变命运了。

如果你本身就具有国际平台运营的经验，那么你可以充分发挥到steem里面，欢迎分享和@我，人多了我们可以建群。
好了，大概就是以上几点， 最后感谢cn区的@dapeng，@sweetsssj，@skenan等等大牛，感谢你们为我们中文区用户打下了坚实基础！
## 延伸阅读：原创，抄袭，洗稿 {#ysyd_yc_cx_xg}

