# (PART) 中级篇 {#zjp .unnumbered} 

# 融入社区 ^[作者：\@wilhb81]
Steemit是一个充满无限可能性的平台。小智是这篇文章的主角，也是他推荐其好友 - 小雅参与Steemit的。

虽然小雅基本已经脱离新手期，但是Steemit是个多元化的社区，她得想办法尽快融入这个社区，与伙伴们打成一片。

小智为了小雅，牺牲自己的时间，特地为她编写一个《如何完美融入steemit社区》的教程。

这个教程包含了以下的四大范围：

Steem上的社交 （这里将会列出在Steem上如何有效与来自世界各地的伙伴们互动与社交）
- 1.善用标签 （列出不同种类的标签以及如何将其运用在文章里）
- 2.Steem上的活动：月旦评和其他 （把Steem上的活动与竞赛介绍给新人和前辈们，同时呼吁他们一起参与其中）
- 3.Steem跟其他社交网站有何不同 （将Steem和其他现有的社交平台做比较，解释他的与众不同之处）
希望小雅能够体会到，小智的用心良苦，把这个《如何完美融入steemit社区》的教程，从头到尾给细读一遍。

## steemit是一个用思想来社交的平台^[作者：\@tvb;编辑:\@maiyude;]

steemit是文学平台？想法平台？社交平台？
steemit是一个用思想来社交的平台——你以为是你的面孔或身体在社交吗？

> Is steemit a literary platform? Idea platform? Social platform?
> Steemit is a social platform with thought.
> Do you think you are socializing with your face or body?

- （一）steemit不是一个文学平台
- 　　　Steemit is not a literary platform

首先，steemit不是一个文学平台。因为还很多朋友分享旅游中的美景和美食，还有很多朋友分享自己在生活中的感动。还有人写读书笔记，写科普知识，代码和数学等等。
所以这决不是一个文学平台，而是一个内容平台。至于内容，只要是真实的、原创的我觉得都应该鼓励。甚至一些略有负面情绪的文章，我觉得只要是作者那一刻真实的感受，我觉得都应该包容。

当然，在包容的基础上，我们应该开导作者，让作者可以更乐观、更积极的面对生活。而这一个沟通、互动和开导的过程，就是社交行为。

- （二）steemit是一个想法平台
- 　　　Steemit is an idea platform
\@deanliu 刘老师说steemit是一个想法平台。这句话绝对是正确的。熟悉我的人应该知道，我喜欢写诗。坦白说，我的诗水平一般。因为读书少，我能写出的词汇和语言都不丰富，但是我尽量在诗中表达一个核心的思想。比如白头偕老的爱情、逆境中的乐观、一年之计在于秋等。

\@lemooljiang 是我非常喜欢的一位作者，他已连载了198期时代之歌。我认真读过他的诗，他写的绝不仅是诗。他在诗中表达了很多的思想。比如他把steemit比喻成一个许愿池，我觉得这个比喻是如此形象而又温暖。

\@coldhair 是典型的想法型作者，在他的文章中并没有像诗一样的语言。但是，包括医学科普常识和许多思考，都可以感觉到一个有深度的医生对职业和世界的思考。

\@sweetsssj 是CN区的女神。最初，我也以为她的文章里就是美景和美女呗，我很不以为然。但是，我最近在她的文章里看到这样一段话“ 剧院里传来人们歌唱的声音，虽然是土耳其文，但是我仿佛听懂了歌声里诉说的生命，夕阳的余晖披泽万物，更显出古城岁月的沧桑荒凉之感。” 我顿时为我自己的狭隘、无知和肤浅感到无地自容。于是我仔细观看了她的文章，她的图片排列充满逻辑，图片内容除了美感，也带来很多异国文化的震撼。她的语言，更加是充满了思想的美感和感染力。

\@helene （本来是称呼画家，她不让）。 我对画是一窍不通，我只是感觉看她的画，感觉很享受。她在一幅秋天的画中写到“ 秋日漫漫，走在林间小道之中，落叶撒了一地。没有什么力量可以让它们重回枝头，这是一种自然的过程，仿佛人生的晚境。它们最后将深入泥土，化为淤肥，滋养另一批新的生命。或许它们的梦想已经破灭，但是它们还是如此优雅的飘落，这大概就是落叶的美丽的瞬间吧。”我再看她画，画面上也满满的是秋的丰富、惬意和烂漫之感。我只能说，她的画，是有生命、有思想的。

\@oflyhigh 和 \@justyy \@dapeng \@magicmonk，正是考虑到我们在使用中的不便，所以生产了很多想法，开发了各种实用工具。

\@rivalhw \@jubi @\kenchung 等等朋友分别举行了有创意、有意义的活动，这实在是灵感的绚丽花火。

还有其他更多元的灵魂作者。 比如 \@mrpointp 健身文章 \@mrspointm 的书法......还有一些朋友研究电子货币，原谅我对这方面不太关注。不能逐一列举。

总之，这些作者的文章和活动，无不吸引着大家。这些例子都说明，语言也好、图片也罢，吸引人的不是内容本身，而内容背后的思想。
所以，这是不止是一个内容平台，更主要的是想法的平台。

- （三）steemit是社交平台
- 　　　Steemit is an social platform

steemit是社交平台吗？

1.先来看，什么是社交(来自于百度百科的解释 )：

> 指社会上人与人的交际往来，是人们运用一定的方式（工具）传递信息、交流思想的意识，以达到某种目的社会各项活动。

2.再来想想steemit

（1）steemit是一个社会

社交首先是社会活动，是社会上的人际往来。那么，什么是社会呢？在社会学中，社会指的是由有一定联系、相互依存的人们组成的超乎个人的、有机的整体。

显然steemit上我们，是有互联系的。点赞就是基本的联系。steemit上的我们的收入会随着steem价格而波动，而我们互动的程度，也会影响着整个steemit的总体价值。假如我们所有人每天只点出10个赞，那么这个steemit区块链上增加的steem是固定的。只有我们加强互相之间的互动，steem的总价值才能更多。这就意味道着steemit的我们，其实是一个相互依存的有机整机。

所以，steemit是一个社会（叫社区也可以）。这意味着，在steemit上的人际往来，是一种必要的行为。

（2）steemit是信息传递

第二，社交是人们运用一定的方式（工具）传递信息、交流思想的意识。

这无容置疑，steemit本身就是在传递信息和交流思想。每一种类型的文章的都是信息，submit a story，其本质是submit some information。而前面我说过，这是一个想法的平台，所以我们其实是submit some thoughts。

（3）steemit可以达成我们的目的

第三，社会是以达到某种目的活动。
无论我们来到steemit是为了交友、写文章，或者粗暴的说，我就是为了挣钱。我们都是为了达到某种目的来到steemit的。

从以上三点来看，steemit是一个社会，我们在这个社会中为了某种目的交流思想。所以我们submit、reply、vote等等，都是社交行为，steemit是一个社交平台。

- （四）steemit是一个用思想来社交的平台

　　　Steemit is a platform with social of thought
那么，steemit到底是社交平台，还是想法平台呢？我是应该努力写文章还是社交呢？

说实在的，这个问题困扰我很久。

1.社交是必要的

本人也做过自我介绍，36岁但只有5个月的工作时间，实在不擅长社交。但是我一个新人，会有人什么看我的贴，关注并给我点赞呢？
于是我开始了我漫长的社交之旅，每天点开cn节点，按new排序，尽量去reply别人的文章。

效果还是比较理想的，我果然获得了超过我实力的关注度。

这说明，社交是必要的。

2.社交是不充分的
然而，在不久，我的文章就回归到20美元了。我老公很认真的批评了我，他说我的文字语言不流畅，而且感情不够丰富。于是我认真的反省了自己的行为。

社交，真的是足够了吗？答案是否定的。于是我开始认真的写文章，写完以后要修改、修改再修改，还要让老公帮我看看，再反复修改以后才发表。

效果果然不同，文章的价格开始上升了。这说明：

在steemit上想要达成自己的目的，社交是必要，但不充分的。

4.写作很必要
而写作呢，的确有很多我未社交过的账号为我点赞，而且并不是每一篇。我相信，所有的新人或小鱼，都会有这样的经历。

我们的文章总有一些思想，可以打动另一些人，那些人和我们在steemit上从未谋面，也无交集。

还有一些人，我努力和他们拉关系（此做法为错误演示，请勿模仿），可是他们仍然不愿送出vote给我。所以，光靠社交是不够的。

写作是很必要的！！

3.思想的社交
于是我困惑了，难道我应该专心写文章，从此不理其他作者？

或者，我仅仅去找大神抱大腿？

可是很多新人的文章仍然是让我爱不释手。比如 \@renzhichu 她的文章总是充满对社会现象的思考。 \@berlin1997 他的文笔犹如游龙，自如而洒脱。 \@dancingapple 她的微型小说，让人回味无穷，而她经常展示一些精美的传统书画，也不容我错过......

所以认真的思考我在现实生活中的社交。我有没有努力的巴结过谁？没有。 我有没有克意的孤立自已？也没有。

对于我喜欢的朋友，我会情不自禁的他的生日、节日或其他时间主动联系他。而对于并不投缘的朋友，他们主动联系我，我也是很简单的回复，久而久之，自然疏远。

所以我何不如此自然的在steemit上社交呢，既不张扬，也不谢绝。每天工作之余，点开feed和新文章看看。每天发文之后，到处逛逛。看看自己的reply，感觉思想上有碰撞的，就回复一下。或者轻轻的回复——谢谢你的关注。

对于一些有兴趣的文章，就真诚的reply。对于我不能完全同意的，我也会认真的reply我的观点。

认真的去阅读和体会朋友们的思想，包括老用户和新人。

4.让思想插上翅膀

而在写文章的内容方面，比如我最近的文章，关于秋天的成长与转折。有137个赞，但只有53个人浏览。从回复来看，能大概读过的文章的人屈指可数。这说明我的文章并不具有可读性，我想在文章中表达的思想也并不鲜明，我的表达方式也需要调整。

所以，我觉得，我应该提高自己的写作能力，用一种更直观、更生动的方式来传递我对秋天、或者情感的想法，让它们真正的走进其他steemitans的心中。

自然的社交，真诚而努力的写作，走进朋友们的思想，同时把自己的想法更自然的传达。



其实呢，我想说，写这下这篇文章呢，主要就是想彰显，我其实是一个有想法的作者。
虽然实际上，我并没有什么思想，但是，在社交中向各位steemit朋友学习，启发我的想法，再进行创作，这是我努力的方向！

特别感谢 \@tumutanzi ，没有坛兄，我永远也不可能知道这样一个用思想来社交的平台！
特别感谢 \@mrspointm ，翻译思想这个词的时候给我指出了用词不当。

还是用小诗来结语吧：

让思想插上翅膀，在steemit的天空下，轻盈的飞翔。

风若助之，我便轻舞。风若逆之，亦可奋进。

与其他人，或探肩而过，或微笑倾谈，或携手同行一段。

总会越飞越高吧！

结语
其实我想表达的是：
只有我们深刻的思考，写在我们的文章里。同时也深刻的去体会其他的作者。才能让我们获得更大的成功和满足感。
只有思想，才能让steemit更放异彩，在区块链中获得更广阔的发展空间。

## steem 上的社交 ^[作者：\@wilhb81]
本章的主人公 - 小智是Steem中期的成员。他在2017年3月8日加入Steem的大家庭（嗯，那天也是三八妇女节，对小智来讲印象也比较深刻）

中期的Steem平台，已经比早期来的更为完善与有系统化，但是有很多方面，还是需要靠自己去摸索。

身为中期的CN社区“砥柱中流”之一的成员，小智深感CN社区的成员极度缺乏，前来给他的文章留言的伙伴们，来来去去都是那几个。

也许CN社区在当时还是属于小区，人数屈指可数。久而久之，小智与他们建立了良好的关系。

每当小智一发帖，那些伙伴们都会蜂拥而至，前来为他留言。看到一大堆熟悉的留言，小智的内心顿时觉得非常温馨。

他也察觉到，Steem不单单是一个让人发挥自身才艺的平台，她也是一个汇集了世界各地每个角落，不同行业背景，不同种族肤色，不同宗教信仰的大杂烩。虽然把很多种不同的食材统统放进一个锅，但是所炖出来的味道，却是无比的美味可口！

鉴于这个点，坚固了他对Steem的信心。他决定采访数位在初期与中期参与Steem的前辈们，让大家能更加了解前辈们对Steem的看法以及他们对Steem的未来展望。

今天，第一位登场的是来自香港的大佬之一：\@aaronli 这位前辈，非常擅长拍摄。他最拿手之处 – 把香港各个角落，用相机给捕捉下来，让后再图文并茂，述说其照片后的历史。每次阅读他的文章，犹如坐上叮当的时光机，快速回溯到百多年前的香港，一窥当时的盛事美态。

话不多说，我把 \@aaronli 前辈的专访给大家呈上，请趁热享用～

注意：由于他用繁体字，我为了尊重本人的意愿，就不多加更改成简体字。

您是几时加入Steemit?

我加入的日期是17年6月14日，至今已差不多9個月了，時間過得真快～

您从哪里得知关于Steemit?

這個就有趣了，那時我在香港一個很熱的討論區看一些關於網賺的帖，看到了\@htliao介紹steemit，就抱著一試心態登記了，沒想到一直玩到現在～

您个人对Steemit有何看法?

我認為Steemit是一個機會，也是很體驗現實的社區，我想每個人都是因為能賺steem及SBD才進steemit的吧～

你會發現steemit其實是社會縮影，你要在steemit成功，就需要人脈、投資，或很有特色的文章，這不是跟社會一模一樣嗎？

不過，Steemit亦讓你認識到不同的國界，題材，還有朋友！當然，在任何社群都有這個效果，但建基於「讓用戶獎賞有價值的文章」下，大家都更熱衷於這個社區～

至於steem自身，我也不知道這個機制是好是壞，但它至少給了我們一個機會，我是看好它的未來的，至少steemshot, dlive, dtube等都選擇了steem，期待steem及SBD今年升到\$20！

是否可以分享您在Steemit的社交秘诀与心得?

很簡單也很殘酷，不論你想賺steem，還是想更多人看到你的文章，你都要做社交，亦需要得到大戶點贊。社交秘訣只有兩樣，一是多點在大戶的文章回覆，讓他認識你，不過不要只留那些「很捧」，「支持你」的留言，你要細心看他的文章，再認真的！

第二是寫好你的文章，否則大戶留意到你都不會點贊你的廢文或水文，我建議新人應建立一個主題，如攝影、如畫畫、如投資，如旅遊，最好有50%或以上的文章都是關於這個主題，這會讓其他用戶更快對你有印象！

（以上的做法是比較功利的做法，請看以下的補充）

最后，还有什么想要补充吗?

堅持。在Steemit要得到好的payout，越遲加入會變得越難，不過只要堅持寫好的文章，努力社交，如參加比賽、活動等，很快就會被其他人留意到！當然，在社交的時候，不要只顧著大戶，小戶都是未來的大戶，也是可以並肩的戰友！

我在Steemit初期，一個人都不認識，也都是認識了香港區的新人們，大家一起扶持才能成長。不要看我現在的文章每篇都有百多vote，雖然跟大戶相比還有一段距離，但都是經過一番努力才能得到的！總之，好文章、好社交，堅持，能讓你在Steem成功。

最後，在社交的時候，不要忘記本心，寫你最愛的題材，寫你從心認同的題材，社交固然重要，但不要為了討好某大戶而寫一些違心的文章，這樣你是堅持不了多久！

Payout自然吸引，不過，平常心更重要，不要只為賺Steem而寫一些自己本來就不太喜歡的東西，或很功利地只討好大戶，所謂日久見人心，其他用戶很快會知道的，我也曾經只有幾塊錢一個post，但我也是堅持寫好自己的文章，和與其他用戶保持交流，今天才可以平均幾十塊一個post。

這個過程是漫長的，在Steemit其實就是經營自己的品牌，你會認為很快就有很好的收獲嗎？不可能，但是慢慢的努力，你的付出一定會有回報，Steemit可以讓你在少於一年的時間就得到好的回報，比其他社群或媒介已經好很多了！

加油。

（注释：文中“steem”是指steem区块链，steemit则是指steemit社区）


## 善用标签 {#sybq}
## steem 上的活动：月旦评和其他 ^[作者：\@wilburm]

相信不少人加入 Steemit 的原因，都是被“写写文字就能赚钱”这个噱头给吸引，就像中文官网欢迎页面上所宣传的那样——你的思想是有价值的，快来加入一个给文章付钱的社区。除此之外，Steemit 网站基于 Steem 区块链的去中心化属性，可能也是另一个值得叫嚣的“卖点”。在当下很多人大谈特谈所谓“去中心化”，以及未来区块链科技大势所趋的前提下，Steemit 似乎给了人们一个错觉——普通人在这里也能靠码字赚钱，像很多内容平台上的大 V 一样。

不可否认，在 Steemit 上持续提供原创内容，的确是可以赚到钱的。赚多赚少暂且不说，内容优质与否自己也大概知道。试想一下，倘若同样的内容上传到其他平台，你敢保证自己也能获得同等报酬吗？这个答案可参考自己平时看到优质内容时的付费（赞赏）意愿。相对来说，Steemit 中文官网“妙笔生金”四个大字，起码是有保证收入这点意愿的。但意愿终归只是意愿，“奖励池”放在面前，能不能拿得到，就得靠自身努力了。

想要更多地获得“奖励池”中的奖金，除了写好文章之外，不能忘了另一个同样重要的“秘诀”——社交，Steemit 毕竟也是一个社区。类似于朋友圈中的礼尚往来，想要获得别人点赞，不能只是孤芳自赏，也得主动多跟别人互动。在一个社区混熟脸后，获得点赞也相比之前要容易得多。对刚加入社区的新人来说，最有效的社交自然要属参加活动不可。很多新人也正是在参加各种活动之后，才获得一笔较大收入，获奖之后自然也就得以被更多人知道。

勤于参加各种活动，显然是个社交方面的捷径。Steemit 上不乏丰富多彩的活动，这里就中文区的活动做个简单介绍。由于活动规则可能会随着时间进行改动，仅供参考。

月旦评

主办：大伟哥 \@rivalhw

文章主题：主题不限，须个人原创

格式要求：标题须加“月旦评”三字，标签须加“cn-reader”

建议：文学题材标签 “cn-literature”，艺术题材标签 “cn-art”

三个一

主办：一姐 \@tvb

文章主题：一诗，不要求原创；一画，一张照片，须原创；一心声，即写的原创文章。（注：一诗、一画、一心声，三者必须全部与主题相关，主题字眼每期更新）

格式要求：第一标签必须为“cn”，其中一个标签须有“cn-31”（注：文章最多加五个标签，第一标签不可更改）

建议：可同时参加“月旦评”活动

华语好声音

主办：一姐 \@tvb

文章主题：一首自唱歌曲，主题字眼每期更新，一段与歌曲相关文字

格式要求：须本人自唱或自奏，普通话、方言均可。标题须加“ X 好声音”（X 即主题字眼），标签须加“cn-voice”

建议：找人合唱

齐白石杯

主办：才女 \@angelina6688

文章主题：原创绘画作品，主题字眼每期更新

格式要求：标题须加“齐白石杯”四字，标签须加“cn-drawing”，绘图步骤三张以上

建议：可同时加“cn-art”标签
（未完）

## “月旦评”投稿禁忌 ^[作者：\@dapeng，原文链接：https://steemit.com/cn/@dapeng/or-one-month-as-a-monthly-review-s-reviewer]


**禁忌之一：空档期投稿。**

月旦评的评奖流程是：你投稿——评委推荐入围（每周一轮）——全民投票（每月一次）——评奖。

这个流程里，有一段青黄不接的空档期。如果你在这个空档期投稿，是很难被推荐的。这个空档期就是：

**\@rivalhw 发布某期的“第 4 轮推荐”帖到下一期的“月旦评第 n 期正式开始”帖之间。**

**不要在空档期投稿。**投了也没有评委读。就算有评委读并且下次推荐了，到时候已经没法点赞和 resteem 了。

**禁忌之二：搬运。**

有的作者来 steem 之前，在别处发布过很多好文章，于是把旧帖重发，来参加月旦评活动。这个问题在 steem 上存在已久，颇有争议。单说月旦评的话，我从评委角度明确表态：这样很吃亏。

症结在于，评委在别处读到了原文，无从判断你的投稿是原创还是抄袭。

你当然可以自证清白，但是这会花费评委的时间。目前的状况是，投稿很多，评委很忙，没时间听你自证。

这样看似不公平，但实属无奈。评委如果把时间花在是否原创的判断上，就会没时间去读其他的首发原创帖，造成更大的不公平。

反正我遇到这种情况的做法就是跳过不理。如果有时间，我大概会要求作者证明一下，如果作者没有回应，我会认为是抄袭，说不定踩一脚。瞧，一来二去时间就搭进去了，我闲得慌吗？

更要命的是，如果这种情况在同一作者身上频频发生，就会进入我的黑名单，以后别管投什么稿，我都一概不读，除非我很闲。

**为了证明是原创，请首发 steem。**在评委时间稀缺的情况下，首发会比搬运获得更高的优先权。

**禁忌之三：洗稿。**

什么是洗稿？不多解释，请自行搜索“六神磊磊 周冲 洗稿”。

在我看来，洗稿比抄袭更恶劣。抄袭相对容易判断一些，而洗稿就困难得多，很容易漏网。揣着明白装糊涂，这是对读者和评委赤裸裸的挑衅和调戏。所以，一旦发现洗稿的作者，哪怕只有一次，就会进入我的黑名单。

**请勿洗稿。**

当然，抄袭就更不用说了。

**禁忌之四：烂帖。**

这么措辞大概比较刻薄，但是为了加深印象，我只能出此下策了。

如今的新人成长很困难，我完全理解有些作者的心情，为了引起注意，不管什么文章，都往“月旦评”投稿，哪怕是烂帖。这对“月旦评”活动也许有一点积极作用，看起来繁荣一些，但属于虚假繁荣，害的首先是作者本人，其次是其他作者——评委的时间被烂帖消耗了。

如果我发现有作者总是拿烂帖投稿，就会丧失对这位作者的兴趣，以后哪怕写得好，我也会跳过不读。没办法，注意力有限啊。

**不要滥用“月旦评”。**

那么，怎么判断自己的帖子烂不烂？什么样的文章才能入围？什么样的文章评分高？

以下是我个人作为评委的建议，不代表“月旦评”其他评委。如有雷同，纯属巧合。

- 基本要求：真情实感。不满足这一条的话，很难入围。
- 第一加分项：思想性。得有让人眼前一亮的想法。满足这一条，我就愿意推荐入围了。
- 第二加分项：文笔。
- 第三加分项：知识性。
- 第四加分项：趣味性。

为什么是以上顺序？难道不应该首先比文笔吗？

因为 steem 的本质，是个社交平台。我们要交往的，是你这个人啊。

## 延伸阅读：steem 跟其他社交网站有何不同 ^[作者：\@maiyude]

说起steem 跟其他社交网站有何不同，我们需要先了解一个概念，什么是steem？

steem是一个通过加密货币奖励支持社区建设和社交互动的区块链数据库。steem结合了社交媒体概念，以及加密货币及其社区建设过程中的经验教训。激励人们参与社区，货币或自由市场经济，一个重要关键点在于，一种公平的，能连贯一致地反映每个人贡献的记账系统。steem是第一个尝试精确，透明地对无数个对其社区做出主观性（subjective）贡献的个体做出奖励的加密货币。

通过steem的概念我们可以看到steem的一个最大的特点，那就是steem有加密货币作为奖励。相比现在的传统社交媒体平台，贡献者们在这些平台上默默的奉献自己的文章，但是最终这些贡献者多数是没有回报的，这些回报都进入到了平台创建者的手里。而Steem最有吸引力的一点就是，你的贡献会直接用加密货币支付给你。

简单点说，Steem和传统社区最不同的一点就是：你的每一个字都有价值，并且你的价值能通过加密货币数量直接体现。

但是steem最核心的一点还是steem是一个去中心化社区，去中心化是什么？关于去中心化的特点和优势不是本文讨论的范畴，我们只要知道因为steem是基于区块链的社交社区，所以它拥有区块链的特点：历史记录不能篡改以及逃避审查。

历史记录能不能篡改是区分是否去中心化的一个关键点，这就是steem与传统社区最大的不同，你在这里做的一切都会记录在区块链上并且不能篡改。

至于逃避审查这一点，很多朋友可能会担心那岂不是在steem可以随意发一些黄赌毒的信息？这个你大可放心，所谓的逃避审查和不可篡改指的是底层技术，建立在steem区块链上的Steemit社区自有它的规则可以避免黄赌毒和垃圾信息的泛滥。steemit社区上有踩的规则，人人都可以踩，也就是其实人人都是审查员，一些黄赌毒的违法信息会很自然的被人踩下去，并导致这些信息不可见。而发布这些信息的人，由于信息不可以删改，他的行为会被区块链永远的记录下来，作为牢牢的罪证。从这一点看，在这里发布违法信息，风险比在中心化社区还要高。

看完了这些，是不是对steem与传统社区的异同有了一些了解。那么接下来，我们再看看steem和现在区块链上的同类项目有什么异同？

我们可以拿steem和现在较为成熟的币乎做对比，币乎其实算是一个伪去中心化社区，币乎其实只是一个使用加密货币作为奖励手段的传统社区。我们前面说过历史记录不能篡改和逃避审查是区分是否中心化的一个标志，从这点看，币乎是存在审查的，而且记录是可以修改的，所以我们说币乎不是一个去中心化社区。

这是steem和币乎的根本性差别，其次我们看看双方的内容。

币乎想做的是一个垂直代币投资者的社区。steem是一个大而全的社交媒体。

这是什么意思呢？就是说币乎讨论的几乎都是有关区块链的信息，是一个较为专注某一领域的社区。而steem要做的是一个大而全的社交媒体。

steem有多大有多全呢？现在我们最常使用的steemit，是建立在steem区块链上的一个应用而已。steem区块链上还有很多其他的应用，比如视频类的Dtube、音频类的Dsound、开源项目奖励Utopian.io、论坛类的Chainbb等等。

那么多的应用，看起来是不是很丰富很全面，但是这还不算，未来steem还有SMTs（Smart Media Tokens），这意味着什么？这意味着STEEM未来会形成一个类似以太坊的生态圈，里面各种内容应用都可以使用STEEM提供的接口生成自己的SMT代币。也就是说，未来所有人都可以自由的在steem区块链上建立自己的应用。这会带来什么样的改变？现存的传统社区，只要愿意，可以轻松的使用SMTs，轻松的接入数字货币，这野心够大的吧？

再来看看币乎，steem区块链上的一个应用steemit社区中的一个标签就可以实现币乎的所有功能。对比之下，币乎的格局确实是小。

## 延伸阅读：“月旦评”给 steem 的启发和教训 ^[作者：\@dapeng，原文链接：https://steemit.com/cn/@dapeng/steem-or]

1

身为草根，有点理想的，都想改变命运。古人也是。如果无产阶级永远看不到奔小康的希望，就会不服，就会闹事，社会就会动荡，那么朝廷拿什么安抚民心？

答案是科举。

朝廷说：你看，不是没给你们机会哦，是你们自己不争气，考不上而已。于是就可以把责任归结到个人头上了。草根们对视两眼，得了，造反不就是为了当官嘛，那还不如考试，考砸了大不了再考，而造反造砸了是要砍头，于是也都心服口服，纷纷当范进，毕生精力都扑到考试上，没工夫谋反。于是，社会就稳定了。

科举制这项伟大的发明，是隋唐时期才出现的，官民双赢，所以一直持续了一千多年，到民国才结束。科举制发明之前，平民的上升通道，是魏晋开始的九品中正制。而九品中正制的前身，就是汉朝的察举制。也就是常说的“举孝廉”。

谁孝顺（父父子子），谁清廉（君君臣臣），大家给他的评价就好，就举荐他做官。而大家的评价里，大 V 的评价最重要。这就是为什么三国时期评人之风盛行，包括出现了每月一评的“月旦评”。相当于每年的高考和模拟考，多来几次嘛，大家都指望靠这个当官发财改变世界呢。

于是，曹操带着胆子来了，投了个稿，大 V 许邵就有胆评。“治世之能臣，乱世之奸雄”，这是他给曹操的评价。大 V 评价的影响力大不大？大。影响后世两千年。目测还会继续影响下去，估计曹操“奸雄”的黑锅得背到人类灭绝的那一天了。

不只是许邵。当时的另一位大 V，人称“水镜先生”的司马徽，也有过一条著名评价，后来由徐庶转达给了刘备：“伏龙凤雏得一可安天下。”伏龙是诸葛亮，凤雏是庞统。这条评价直接影响到诸葛亮的后半生，乃至后世对诸葛亮的神化，为千年后写成的不朽名著《三国演义》奠定了基调，确定了第一男主角。


2

靠大 V 的点赞来“举孝廉”，算是布衣的一条出路。有出路比没出路好。但是，受历史局限性，这个制度有很多弊病。

弊端之一，就是为名所累。三国有段著名的故事：徐庶走马荐诸葛，刘关张三顾茅庐。为什么徐庶一听母亲被曹操软禁，就立刻离开刘备（走之前推荐了诸葛亮来接班）投奔曹操了？亲情是感情上的原因；而基于现实的考量，一旦担上“不孝”的恶名，完了，以后别想混了，必被别的孝子取代。往轻了说是职业生涯就此断送，往重了说……看看孔融吧，三岁让梨的孔融，孔子的嫡子孙孔融，建安七子的大文学家孔融，被安上了个不孝的罪名，给满门抄斩了。灭门的时候，他家的娃还留下个“覆巢之下岂有完卵”的成语。

为了名声好，当时葬礼奢华之风盛行。孝嘛，绞尽脑汁，也得要个孝顺的名声啊。父母去世了，就倾家荡产办丧事，一辈子的积蓄全埋到父母的坟墓里，一守孝就是好几年，期间连夫妻生活都不能有。后世的盗墓贼，最喜欢盗的就是东汉的墓，里面全是金银珠宝。曹操为此痛心疾首：咱们汉朝的 GDP 不低啊，可是咱们把钱都埋了啊。所以，曹操去世时前立下遗嘱，要薄葬，自己带头，煞一煞不正之风。

弊端之二，是拉帮结派。

读三国，会发现一个特别的现象，那就是很多人才，都来自“颍川”这个神奇的地方（今属河南）。前面说的司马徽和徐庶，就是颍川人（这么说来，诸葛亮的名声是出自颍川）。还有郭嘉、钟会、钟繇、荀彧、荀攸......等等等等。难道是别的地方风水太差，就我们河南人才多？

不是。其实是因为抱团取暖，大家相互点赞，一人独吹不是春，大家互吹春满园，于是越做越大。这些名人未必全部有才，但其中有才的人，必须在出名之后，才华才有地方能施展得开。事实证明，别的地方也是人才济济，例如江东，但是当时被我们这些河南人的名气 给盖过了。就好比 steem 上草根的文章写得再好，也难上流行热门榜，因为被大鲸们的互赞给盖住了。

这造成了人们对许邵“月旦评”的负面评价。有人说月旦评过于主观，有人说月旦评结党营私。《后汉书》认为月旦评是许劭用来攻击他哥哥许靖的工具。诸葛亮的侄子诸葛恪（后来在东吴权倾朝野），曾经给东吴丞相陆逊的信里写道：

> 都特么是许邵这帮人互相吹捧诽谤搞出的事儿。
>
>（自汉末以来，中国士大夫如许子将辈，所以更相谤讪，或至于祸，原其本起，非为大雠。惟坐克己不能尽如礼，而责人专以正义。）

3

三国时期的这个情况，跟 steem 很像。

你是草根吗？天天看着自己可怜巴巴的 SP，发的帖子质量不见得比大鲸写得差，但人家是上百 SBD，而你只有几分钱的收入，没人赞没人看，根本看不到未来的出路。怎么办？

要是你只想躬耕于南阳，不求闻达于诸侯，那就维持现状挺好；否则，有两条出路。

第一条，上文已经介绍了：得靠大鲸的点赞。

得傍大腿啊，同学！这里没有科举制，不是谁考卷写得好就能上名校！这些天来，你乌泱乌泱地发帖，可是你拜过码头了吗？去过颍川了吗？

你就算是诸葛亮满腹经纶，那也得靠大 V 帮你把名声打出去，才有刘皇叔来顾你家茅庐呀！每天光中文区就四百篇文章，你不想想办法的话，你的文章惊天地泣鬼神，可是哪个人类能看得见啊！

那么谁是大 V？

“月旦评”活动里，主办人 @rivalhw 就是水镜先生啊！@rivalhw 在 [华语水浒英雄榜](https://cnsteem.com/cn/@dapeng/6mnla8-steemit-cn)位列第四，对应梁山角色是天闲星公孙胜，手持 6 万 SP，如果给你全力点赞一次，你的帖子就会得到 15 SBD（约合 1000 元人民币）的收益。更庆幸的是，@rivalhw 的爱好不是马术高尔夫球这种高不可攀的贵族活动，而是原创文字！也就是你小学就会的作！文！——那还等什么，赶紧去抱啊。

还有“月旦评”的评委们， @deanliu @lemooljiang @tumutanzi，这些都是声望 69 以上的大 V ！ 还有 @hannahwu，虽然目前声望略逊，但那也是独立博客圈响当当的狠角色，在 steem 上的前途不可估量！若是这些人你都不喜欢的话，去水浒英雄榜上找别的大  V  啊！只要他们给你一个赞，胜过草根点你千赞万赞啊！

怎么抱大腿？

参加他们举办的活动，写他们推崇的东西啊！去他们府上（主页）拜访，看看他们自己都写些什么，看看他们都给谁点赞给谁留言。你再留个言就等于递个名片，人家才知道你的存在啊。

你说你喜欢我行我素，不屑于取悦他人。是，我佩服有骨气的人。可是，大 V 的喜好不只一个，总有个跟你不谋而合心相印的吧？你不用屈尊拍马屁，只需找对人，交个志同道合的大 V 朋友，你才能越写越好，越写越开心，而且同时有钱赚啊！要不然，你还不如躬耕于新浪博客和 wordpress；来 steem 界面丑发帖慢编辑器难用，你说你图个啥？

第二条，上面其实也暗示了，得抓机遇。

诸葛亮虽然被大 V 点赞，但是为什么不去 SP  最多的曹操阵营，而去了屌丝刘备阵营？因为那里有出头的机会。曹操阵营人才太多，嗷嗷待赞的也多，每人分的就少，轮不上诸葛亮。而刘备那里，SP 不多，但是对诸葛亮 100% VP 点赞。

这就好比 steem CN 区文章太多，大 V 又少，分给你的赞也不会多。去别的阵营看看，比如现在 Utopian.io 就是很好的机会。趁早去，去得晚了可能机会也就没了。“伏龙凤雏”里的凤雏庞统，同样去抱刘备的大腿，去了一看，刘备左腿趴着关张赵马黄，右腿趴着诸葛亮，满了。最后，伏龙流芳百世，凤雏一事无成。

CN 区之外的阵营有英文门槛，如果迈不过去，也不是没有出路。前几个月 Ned 代理几百万 SP 给几个中文用户，中文区空前繁盛，就是一次机遇。这两天 SBD 疯涨，也算是个机遇。以后还有没有这种机遇，没人知道，但是可以走着瞧。

曹操阵营的司马懿，一开始啥都不是，也没有大 V 点赞，不管发什么帖都沉底，根本没有出头的机会，但是他坚决不换阵营，他能熬。司马懿熬死了自己阵营的曹操，曹丕，曹真，曹爽，还熬死了敌方阵营的诸葛亮。最后，机会终于落到他家头上了，他的儿孙建立了晋朝，取代了矿主。

steem 上，很多老人在多次沉浮里慢慢离去。沉舟侧畔千帆过，新人的地位越来越高，熬成了老人，成为了新一代的大 V。

试试看，你能在 steem 上熬多久？
