# 注意事项 {#zysxp}
## 礼仪规则 {#lygz}
## 个人隐私 {#grys}
关于steemit上的肖像权和隐私权问题

昨天，微信上收到陌生人的消息（我的微信没有开启好友验证，所以任何人都可以直接发消息给我），说是steemit微信群看到我的账号，是新人，希望我给他的文章点赞，并附上了链接。

作为新人，希望自己能快速的融入这个集体，写出来的文章受到认可无可厚非，于是我立刻点开了链接想要去upvote和留言表示支持（我还是浮游生物，点赞的效益趋向于零，哭）。

一点进去我就懵了。微信沟通看起来是个男孩子，但打开帖子进入眼帘的是个漂亮的女孩子的照片，再往下拉，看到两人的合照。回到标题，再细细阅读了文章，大抵是个失恋的故事。

于是我回到微信上，对他说：“如果说分手了的话我建议你把对方的照片删掉吧，合照把对方打上马赛克，这里七天后就不能对文章内容进行修改，毕竟是涉及到对方隐私的事情。”

“我就是想要永久的保存这段记忆和照片。”他回复道。

“要永远保留照片的方式有很多种，你大可以放在网盘或者硬盘中，而不是以这种公开的方式。”我对他说。其实我没说的还有，虽然steemit还是一个比较小众的平台，遇到熟人的可能性会比较低，但难保万分之一的可能真的有熟人。我可以想象如果当事人被朋友提醒，找到帖子来看，心里那种震惊和恐惧的感受。

刚好我今天下午比较空，于是专门去找了关于肖像权和隐私权的资料。

关于肖像权：民法通则规定“公民享有肖像权，未经本人同意，不得以营利为目的使用公民的肖像。”

关于隐私权：隐私权是指自然人享有的私人生活安宁与私人信息秘密依法受到保护，不被他人非法侵扰、知悉、收集、利用和公开的一种人格权，而且权利主体对他人在何种程度上可以介入自己的私生活，对自己的隐私是否向他人公开以及公开的人群范围和程度等具有决定权。隐私权是一种基本人格权利（法学名词）。

从民法通则关于肖像权的规定中我们可以明确的得到两个关键字：未经同意和获得营利。在我遇到的这个例子中，显然那位朋友是没有征得对方同意的，至于营利，即使其发表的主观目的不是赚钱，但大家的点赞是能为他带来收益的。我不是法学专业的，但仅从民法通则的浅显理解来看，这个举动是有侵犯肖像权嫌疑的。

抛开那件特定的事，放眼平时的情况下，要每张照片都得到别人的许可也是不现实的。比如你去参加爱豆的演唱会，拍了现场照片发到社交网站上为爱豆疯狂打call，那时候显然不可能征得照片里每一个人的同意。

因而我觉得，对于非赢利为目的的，应该报以善意且以不给对方的生活带来困扰为前提。如果照片中会出现比较明显的面部特征的时候，是朋友的最好还是征得对方的同意，不然就和对陌生人的处理方式一样，用可爱的“猫猫头”马赛克处理一下吧～当对方要求停止使用其照片的时候，就应该立刻停止。

过去我们在博客、微博、朋友圈等社交平台上发自己的个人照片，总是可以在不想要公开的时候，删掉就好了。但大家不知道的是，其实很多情况下，删除的只是你页面上的显示，通过网页快照或者一些搜索方式，自以为已经删除的照片其实依然可以被有心人翻出来。

这在steemit上就更严苛了，我们都知道留言一旦被回复以后就不能删除，发的post七天后就不能编辑，所以无论是发自己的照片/隐私的事情，还是发别人的，都要慎重啊。
## 图片版权 {#tpbq}
## 关于偷窃 {#gwtq}

