# 机器人 {#jqrp} 
## 机器人之印象篇 ^[作者：\@wangwenjing；编辑：\@dapeng] {#jqrzyxp}
### 机器人概念 {#jqrgn}
从广义上讲，凡是能够代替人类自动执行指定操作从而完成特定功能的，都可以被称为机器人。机器人可以是机械手、iRobot 等实体，也可以是无形的计算机程序。我们将 Steem 上的机器人定义为：“**能够操控 Steem 帐户执行点赞、留言、发帖、操控内部市场等一个或多个功能的计算机程序**”。不难理解， Steem 机器人往往都是与某个特定 Steem 帐户挂钩的。这就是为什么我们经常会听到“某某帐户是机器人”这一说法。事实上，更准确地表达是“某某帐户的行为是由某一个计算机程序来控制的”。这些计算机程序对读者来说是无形的，它依托 Steem 帐户进行物化。除非特殊说明，我们将沿用这一习惯，**将机器人物化为与计算机程序挂钩的 Steem 帐户**。

### 机器人分类 {#jqrfl}
1. 职能机器人

    职能机器人，顾名思义，是指**用来完成指定职能的机器人**。Steem 职能机器人包括但不限于以下几类。

    - 欢迎机器人

    **欢迎机器人是一类通过到处留言，刷存在感的机器人**。这类机器人通常只留言，不点赞。最早的欢迎机器人当属 \@wang。无奈 \@wang 生不逢时，目前声望值以被踩为负数，暂时告别了大家。

    - 点赞机器人

    **点赞机器人是一类专门执行点赞操作的机器人**。这类机器人都会制定自己的点赞算法，主动给用户点赞。当然，由于每个机器人点赞规则不同，因而点赞力度和范围也不尽相同。与欢迎机器人相同的是，点赞机器人一般也会留言，刷存在感；不同的是，点赞机器人的主要目的是通过点赞，获取**点赞收益**。

    - 卖赞机器人

    **卖赞机器人是一类通过收取一定报酬给用户进行点赞的机器人**。事实上，卖赞机器人是一种特殊的点赞机器人，但是一般不会主动点赞。报酬通常是以 SBD 或 Steem 的形式存在。有的卖赞机器人也会接受用用户的**点赞权限**或者**点赞数量**来交换一定的赞。这类机器人一方面通过直接收取报酬来赢利，另一方面通过点赞获取点赞收益。著名的卖赞机器人有 \@randowhale, \@upme, 和 \@minnowbooster 等。

    - 借贷机器人

    **借贷机器人是一类通过收取一定报酬将自身 SP 代理给用户使用的机器人**。借贷机器人往往自身拥有可观 SP，以有偿使用的方式**代理**给用户使用。与卖赞机器人类似，通常也是以收取 SBD 或 Steem 为报酬进行借贷，只是与卖赞机器人相比，借贷机器人收益的报酬要高很多。主流的借贷机器人有 \@blocktrades, \@minnowbooster  等。

    - 发帖机器人

    **发帖机器人是一类代替用户进行自动发帖子的机器人**。根据发帖内容是否预置，还可以细分为**定时发帖机器人**和**写作机器人**。前者需要用户提前将帖子写好，由机器人在指定时间发送。而后者要更复杂一些，因为帖子的内容完全由机器人完成。换言之，写作机器人才是真正意义上的发帖机器人，用户完全不必参与。 cn 区就有不少发帖机器人，例如：\@pzhao, \@chinadaily, \@dailychina, \@arabel 等。这些都是写作机器人，它们分别从不同的角度为我们提供了 Steemit 的一些统计信息。另一写作机器人 \@shentrading  则为我们提供了数字货币交易的信息。

    - 执法机器人 

    **执法机器人是一类以踩帖的方式对 Steem 上发布的内容进行监管的机器人**。它们是活跃在 Steem 上的“警察”，对一些违反其规则的帐户以“踩”的形式进行处罚，并对其他帐户起到了警示的作用。知名的执法机器人有 \@cheetah， \@steemcleaners， \@adm 等。

    - 交易机器人

    **交易机器人是一类代替用户操作内部市场的机器人**。除了写作平台，内部市场也有机器人的身影。 cn 区技术前辈 \@oflyhigh 就曾经使用过机器人来自动操作内部市场对 Steem 进行买卖。这类机器人若想赢利，算法要比其他职能机器人复杂，因而并不多见。  

    - 优质内容发掘机器人

    **优质内容发掘机器人是一类通过幕后团队发现优质内容，并对其点赞的机器人**。本质上讲，优质内容发掘机器人也是一种点赞机器人，只不过幕后有团队发掘优质内容，而不是纯粹为赚取点赞收益而简单粗暴地不区别内容地进行点赞。最著名的优质内容发掘机器人当属 \@curie。

2. 应用程序式机器人

    应用程序式机器人，其实是一种综合性的功能机器人。这类机器人除了与一个特定 Steem 帐户挂钩，还建有自己的网络应用平台，向用户提供多项服务，例如：自动点赞、自动发帖、尾随点赞、自动留言等。与上述机器人不同，这类机器人是通过获取用户的 **posting key** 来**操作用户帐户** 以代替用户执行点赞等操作。较早出现的有 \@steemvoter，功能比较完善的有 \@steemauto。  

3. 全自动和半自动机器人

    通过上述描述我们可以看出，任何 Steemit 帐户都有可能成为机器人，可以通过自己编程，也可以通过使用别人提供的机器人服务。如果某一 Steemit 帐户完全由计算机程序操作，则称为“**全自动机器人**”；否则，则称为“**半自动机器人**”。例如， \@cnbuddy 是一个全自动机器人，因为它的点赞操作完全由外部计算机程序执行，没有掺进人情成份；而 \@justyy 则是一个半自动机器人，因为一方面 YY 银行通过计算机程序自动给股东点赞与发利息，另一方面银行行长也会手动给优质作品点赞。

4. 第三方应用平台点赞机器人

    除了 Steemit，不断涌现出新的基于 Steem 的第三方应用平台，包括 Utopian.io, DTube, DLive, DSound, Zappl等。为鼓励用户使用他们的平台，他们分别推出了自己的点赞机器人，给通过这些平台发布的优质内容进行点赞。目前进行得如火如荼的当属 Utopian.io了。它已经已经在意大利注册了公司，规模在不断壮大，规则在不断完善，堪称第三方应用平台的楷模。

### 本节小结 {#bjxj}
曾几何时，机器人并不受 Steem 平台欢迎，甚至遭到各种抵制。随着机器人性质的转变，有很多机器人越来越受官方及用户喜欢。并且，很多应用平台也推出了自己的机器人。机器人到底好不好，用句老生常谈的话：“存在即合理。”**机器人本身没有任何问题，关键在于我们如何使用它**。真人用户也可能提供垃圾内容，机器人也可以贡献优质内容。希望用户和机器人在 Steem 的平台上可以发挥各自所长，为打造 Steem 美好的明天共同努力！

## 机器人之应用篇 {#jqrzyyp}
### 典型机器人使用指南 {#dxjqrsyzn}

### 机器人之 cn 区专属机器人 cnbuddy 介绍 {#cnbot_cnbuddy}

## 机器人之开发篇 {#jqrzkfp}
### Python Steem API 介绍 {#python_api}

### JavaScript Steem API 介绍 {#JavaScript_api}

### 点赞机器人开发案例 {#upvotebot}

### 发贴机器人开发案例 {#postbot}

