\appendix

# 附录 {#fl}
 
## 我的steem故事

### 我和Steemit的故事[作者:\@sweetsssj]
- 一个机缘巧合上了Steemit
说起第一次点开Steemit的网页，需要把时光机倒带回2016年8月6号那一天，打开网页的那一刻也注定了我与Steemit朝朝暮暮560多日的缘分。

记得在8月初我和微信上的一位好友闲聊的时候，第一次听说了Steemit，日常的我很喜欢写东西和分享照片，所以朋友极力推荐我注册Steemit一试，并鼓励我发文。

那时候的我，对于区块链世界好似一头雾水，所以刚开始的一个月里，我是在不断的摸索和学习中度过的。那时候Steemit对我来说是一个神秘又充满吸引力的新世界。平台上的用户热情又友好，大家畅所欲言，分享生活里的正能量，与此同时，我也结识了一批中文区德才兼备的朋们，并得到大家的鼎力支持。整个中文群气氛温馨又和睦，大家互相帮助，共同成长。

- 刚起步就进入平台低谷期
刚刚起步的Steemit网站，就像稚嫩的新生儿，在学习走路的过程中难免有些跌跌撞撞，但是却从来没有放弃对于成长的渴望。刚开始在Steemit发布图文兼备的文章很不容易，但是随着平台工作人员一点一滴的改善，Steemit的功能越来越多，使用起来也越来越便利。

我必须承认我是一个幸运的人，在Steemit上刚刚开始写作生涯，就得到了几位大鲸鱼的关注，大家的点赞和留言给了我很大的信心继续写作。不过渐渐的，Steemit从币价的高峰期到了它发展阶段的第一个低谷，眼看着周围在平台很有名望的作者逐渐离开，有些伤感。但是我自己依旧对写作兴趣满满，尽管那时候没有再像之前那样得到大鲸鱼的关注，但是我没有灰心，无论赏金多少，还是继续坚持发文，同时努力自学提高文章的质量，并认真的和平台用户互动。从最开始毫无主题的随机发文，到后来渐渐找到了写旅游博客的方向，我一直没有放弃过写作。后来的一次机遇，得到了外国点赞团队的信任，协助发现中文区的优质文章，那个时候还是条小鱼的我通过点赞团队，帮助了很多中文区的优质作者增加收入，让我第一次感受到给予其实比索取更快乐。Steemit是个充满爱的平台，最好的实现了赠人玫瑰，手留余香的概念。

- 和Steemit一起成长是我最幸福的事
如今通过不懈的努力，曾经那条初出茅庐的小鱼也在平台上得到了成长，看着Steemit社群一点点壮大，心中感到无比幸福。陪伴Steemit一起成长，是一件非常愉快的事，希望每一位朋友都能在平台上发现自己的初心，找到属于自己的角落，并成为自己想要成为的人。

### \@yellowbird与steemit的故事 [作者:\@yellowbird;]

我来steemit是自己一路摸索过来的，最早知道steemit是《学习学习再学习》的公众号文章中发现的，然后出于对区块链项目的好奇，就网上搜索尝试了解，那时网上关于steemit的信息不多。

大部分时候，我也只是作为一个旁观者，尝试了解熟悉这个英语网站。英语不好的我开始没太多兴趣（因为大部分看不懂），后来偶然发现有中文的帖子，顺藤摸瓜就找到了steemit里的cn中文社区，原来已经聚集了不少的中文写作者。

通过中文社区的一些文章，我对steemit有了更深入的了解。如果不是中文社区的存在，显然我可能就是个匆匆过客。很快，我开始尝试注册，开始摸索如何发文，摸索如何在steemit里生存，也摸索如何在steemit里成功发起一个活动——steemit中文区“我的2017年终总结”写作活动——活动很成功，有60多人参加，活动也送出了一个34.3SBD的大奖。

我加入steemit是在17年8月份，赶上了一个最好的时候，那时@ned代理了大量的SP给中文区，在中文区众多大鲸的照顾下，我通过写文章很快的发展起来，也赚到了人生中通过写作而获得的最大一笔钱。



因为发现steemit对中文用户不太友好，特别是注册。从加入steemit开始，我就通过自己的实践开始写关于steemit的教程。也因此被邀请加入到《区块链生存训练》的一个社群，写关于steemit相关的内容，也因此认识到更多的行业内牛人。

有不少人通过我关于steemit的分享来到了这里，我得意的当然是推荐了@angelina6688来steemit，她成长速度极快，也许可以成长为未来的大鲸鱼。在分享steemit的道路上，我后来厚着脸皮写了篇《写作四个月，赚到四万元》的文章。标题党的好处让我尝试了人生的更多体验——人生第一次微信语言直播分享，人生第一次线下活动演讲。然后，因为这些假装自己也是个牛人。

steemit于我来说仿佛就是一个魔盒，打开之前你不知道里面会带给你什么，打开之后它让我的2017年多了很多的不一样。

### 苹果树下[作者:\@dancingapple;]

宛若流水飘灯
于幽蓝静谧深处
守一隅昏黄温暖
浮浮荡荡滴滴点点
不耀眼
这样的地方啊
适合抬头
看星星

这个适合看星星的地方，就是dancingapple在steem上的家。

在这里，有理性，有感性，但两者之间并没有什么逻辑。
就像地球与火星的距离，客观存在，主观维系。

在这里，有亲情、友情、爱情，也有其他说不清道不明的各种情，唯独没有假意和虚情。
就像南风过境，你看不见风的模样，但你能站在高岗上，真真切切感受它的变幻无形。

在这里，你可以把每一篇文章都看成一场独舞，文字是每一个细微动作，章节是无声的乐章。
没有卖弄的风情，但有含蓄的性感。
没有精致的脸庞，但有诗意的身段。

我无法在五十年里扫净五百年的尘埃，也无法在五百字里完整阐述\@dancingapple在steem上的故事。

因为熙熙攘攘，相遇才显得意外。

舞只跳给有情人看，文字写给有心人赏。
很庆幸，一路走来，收获了许多同伴。

来到这里写的第一篇文章叫《大树乌有》，仿佛种下了一颗树苗，自那以后，几乎每天我都上来灌溉，不管是暖春还是寒冬。

在这里，我们彼此都是旁观者，彼此都是过客。
我们呈现出来的，是自己最想要的模样。

人来人往，车马喧嚣，我就在这棵没有任何成长逻辑可言的树下，不询你的过去，不问你的未来。
就只在这当下一刻，在steem小城里，与我邻居的你，我愿意倾听你的故事，细看你的模样。

小城故事多，
充满喜和乐。
若是你到小城来，
收获特别多。

文章最后，希望我没有离题……

### 我的Steem的故事 by vickylin[作者:\@vickylin;]

【Steem指南】由\@dapeng发起的项目正在如火如荼的开展中，几乎可以说是一天一个变化。即使是临近过年，大家依然干劲十足的忙碌着。目前我主要参加注意事项篇中个人隐私这块的素材收集和写作，晚点还会在基本常识篇中挑选自己比较熟悉的一块内容进行整理。

说到我的steemit故事，熟悉我的朋友都知道，我是在我们家长老的介绍下开始写的。记得当时，他看了我的影评，对我说：“你文章放在个人博客上，看到的人寥寥无几。放在简书上，虽然叫好但不叫座，等人从口袋里掏出钱来给你打赏，太难了，何况这平台还规定得累积到一百才能提现。你可以把文章发到steemit上去，让文章得到最大的发挥，让更多的人可以看到，更何况还能赚钱呢。”他大概是去年7月份的时候得知这个网站，注册并发布了写文章，但并未上心维护。这使得我后来常调笑他说：“我感觉你错过了个好时代，要是坚持下来，指不定也是条小鱼了。”

自从去年12月开始，我关闭了朋友圈，卸载了微博，对我来说获取外界消息的，一个是当日的报纸，另一个就是推特。推特上戾气太重，实在不适合成为日常阅读的媒体。然而，steemit则不同，这里真的是人才济济。有超级it男神\@skenan，有乐于帮助新人的\@rivalhw \@dapeng\ @justyy，有steemit百事通\@oflyhigh，有万能的\@tvb，有超级奶爸\@mangoanddaddy，有热爱分享生活的\@ace108 \@chann，有摄影达人\@stabilowl，有超级爱看书的妹纸\@weisheng167388，有超赞的\@angelina6688 \@vivia\ @irisz，有文笔超好的\@hannahwu \@dancingapple。我社交能力比较差，目前认识的人还很少，希望在未来的日子里面和更多人结识，在他们身上学习到我所没有的特质。

steemit也让我恢复了写作的习惯。我是一个每天习惯用纸笔记录下日记的人，只是那些太琐碎了。为了拿出不那么水，勉强能看得下去的文章，每天我都得在电脑前起码冥思苦想一个来小时，有时候甚至为了一篇文章花上五六个小时的时间。

目前我主要写的还是电影/电视的推荐、影评以及一些小Geek知识。之前丢失的账号在\@skenan的帮助下也恢复了，希望自己能慢慢找到适合自己的方向，将两个账号的内容隔断开，吸引到不同喜好的读者。我始终对自己说，书写的目的不是赚钱，起码不是主要理由。我是个爱分享的人，如果有人因为看了我分享的东西，使他们的生活添加了快乐，会让我超有成就感。

很开心长老向我介绍了steemit，很感激steemit里大家的陪伴和支持。

未来的日子，请大家也多多指教啦。

谢谢大家的来看我的文章，如果您喜欢的话，请在steemit上关注我\@vickylin，或给我点赞和留言，再次感谢～


